  # docker-compose.yml

  services:
    php:
      image: php:8.2-apache
      volumes:
        - ./src:/var/www/html
      ports:
        - "8000:80"
    
    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: testdb
        MYSQL_USER: user
        MYSQL_PASSWORD: userpass
      ports:
        - "3306:3306"
    
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: rootpass
      ports:
        - "8080:80"
