version: "3.9"

services:
  php:
    image: php:8.2-apache
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: musicSinger
      DB_USER: clarice
      DB_PASS: felix
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: musicSinger
      MYSQL_USER: clarice
      MYSQL_PASSWORD: felix
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
      PMA_ABSOLUTE_URI: http://db:8080/
      PHPMYADMIN_ALLOW_ARBITRARY_SERVER: 1
    ports:
      - "8080:80"